// Jenkinsfile example for Nextlinux Engine compliance and security analysis of a container image in a docker v2 registry.
// This example expects Nextlinux Engine installed and available over the network. It uses curl to interact with Nextlinux Engine API directly
//
// Configure the environment section accordingly before using this snippet in your Jenkins Pipeline.
// Successful run produces the following artifacts in the Jenkins workspace. Use Jenkins archive step (not included) to persist these artifacts.
// Ensure proper cleanup of these artifacts before running the snippet or use some combination of Jenkins job name and build ID in file path of the
// generated artifacts to avoid conflicting with other build results
//
// - nextlinux_vulnerabilities_report.json
// - nextlinux_policy_evaluation_report.json
// - nextlinux_content_report_os.json
// - nextlinux_content_report_files.json
// - nextlinux_content_report_npm.json
// - nextlinux_content_report_gem.json
// - nextlinux_content_report_python.json
// - nextlinux_content_report_java.json


import groovy.json.JsonOutput
import groovy.json.JsonSlurper

pipeline {
  agent any

  stages {
    stage('Nextlinux Scan') {
      environment {
        NEXTLINUX_ENGINE_URL = "http://192.168.1.146:8228/v1"
        NEXTLINUX_ENGINE_CREDENTIALS = credentials('nextlinux-engine-credentials') // Jenkins credentials reference
        NEXTLINUX_ENGINE_POLICY_POLICY_ID = "" // if left blank, nextlinux engine defaults to active bundle for policy evaluation
        NEXTLINUX_ENGINE_ANALYSIS_TIMEOUT_MINUTES = 5 // time in minutes to wait for analysis to complete
        NEXTLINUX_ENGINE_SLEEP_SECONDS = 5 // wait time in seconds between retries
        NEXTLINUX_ENGINE_VULNERABILITIES = "nextlinux_vulnerabilities_report.json"
        NEXTLINUX_ENGINE_POLICY_EVALUATION = "nextlinux_policy_evaluation_report.json"
        NEXTLINUX_ENGINE_CONTENT_PREFIX = "nextlinux_content_report_"

        TAG_TO_BE_ANALYZED = "docker.io/library/alpine:latest"
      }
      steps {
        script {
          node {
            echo "Starting Nextlinux Scan Stage"

            def output = "nextlinux_curl_output"
            def curler = "curl -ks -w '%{http_code}' -u ${NEXTLINUX_ENGINE_CREDENTIALS}"
            def error_msg = ""

            // Add image for analysis. parse digest and analysis state from response
            echo "Adding ${TAG_TO_BE_ANALYZED} to Nextlinux Engine for analysis"
            def request_body = JsonOutput.toJson([tag: "${TAG_TO_BE_ANALYZED}"])
            def cmd = "${curler} -o ${output} -X POST -H 'Content-Type: application/json' -d '${request_body}' '${NEXTLINUX_ENGINE_URL}/images?autosubscribe=false'"
            // echo "cli: ${cmd}"
            def http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              error_msg = readFile(file: output)
              error "Failed to add ${TAG_TO_BE_ANALYZED} to Nextlinux Engine for analysis. HTTP status: ${http_status}, message: ${error_msg}"
            }
            def analysis_response_json = readFile(file: output)
            def analysis_response_map = new JsonSlurper().parseText(analysis_response_json).get(0)
            def image_digest = analysis_response_map.imageDigest
            def analysis_status = analysis_response_map.analysis_status
            analysis_response_map = null // unset to avoid serialization error
            echo "Received image digest: ${image_digest}, analysis status: ${analysis_status}"

            // Get image and check status
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}'"
            echo "Checking analysis status for image digest ${image_digest}"
            timeout (time: "${NEXTLINUX_ENGINE_ANALYSIS_TIMEOUT_MINUTES}", unit: 'MINUTES') {
              while (true) {
                http_status = sh script: cmd, returnStdout: true
                http_status = http_status.trim().toInteger()
                if (http_status != 200 && http_status != 202) {
                  error_msg = readFile(file: output)
                  error "Failed to get image info from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
                }
                def image_response_json = readFile(file: output)
                def image_response_map = new JsonSlurper().parseText(image_response_json).get(0)
                def image_status = image_response_map.analysis_status
                image_response_map = null // unset to avoid serialization error
                if (image_status == 'analyzed') {
                  echo "Image analyzed"
                  break
                } else if (image_status == 'analyzing' || image_status == 'not_analyzed') {
                  echo "Image status is ${image_status}, will retry after ${NEXTLINUX_ENGINE_SLEEP_SECONDS} seconds"
                  sleep time: "${NEXTLINUX_ENGINE_SLEEP_SECONDS}", unit: 'SECONDS'
                } else {
                  error "Failed due to image status ${image_status}"
                }
              }
            }

            // Fetching all reports
            echo "Fetching all reports for image digest ${image_digest}"
            def report_gen_error = false

            // Get vuln report
            echo "Fetching vulnerability listing"
            output = "${NEXTLINUX_ENGINE_VULNERABILITIES}"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/vuln/all'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get vulnerabilities listing from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get policy evaluation report
            echo "Fetching policy evaluation"
            output = "${NEXTLINUX_ENGINE_POLICY_EVALUATION}"
            try { // check for environment variable. this is hacky but there does not seem to be a better way for checking environment variables
              cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/check?policyId=${NEXTLINUX_ENGINE_POLICY_POLICY_ID}&tag=${TAG_TO_BE_ANALYZED}&detail=true'"
            } catch (e) {
              cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/check?tag=${TAG_TO_BE_ANALYZED}&detail=true'"
            }
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get policy evaluation from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get os image content
            echo "Fetching os content"
            output = "${NEXTLINUX_ENGINE_CONTENT_PREFIX}os.json"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/content/os'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get os content from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get files image content
            echo "Fetching files content"
            output = "${NEXTLINUX_ENGINE_CONTENT_PREFIX}files.json"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/content/files'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get files content from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get npm image content
            echo "Fetching npm content"
            output = "${NEXTLINUX_ENGINE_CONTENT_PREFIX}npm.json"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/content/npm'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get npm content from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get gem image content
            echo "Fetching gem content"
            output = "${NEXTLINUX_ENGINE_CONTENT_PREFIX}gem.json"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/content/gem'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get gem content from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get python image content
            echo "Fetching python content"
            output = "${NEXTLINUX_ENGINE_CONTENT_PREFIX}python.json"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/content/python'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get python content from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            // Get java image content
            echo "Fetching java content"
            output = "${NEXTLINUX_ENGINE_CONTENT_PREFIX}java.json"
            cmd = "${curler} -o ${output} -X GET '${NEXTLINUX_ENGINE_URL}/images/${image_digest}/content/java'"
            http_status = sh script: cmd, returnStdout: true
            http_status = http_status.trim().toInteger()
            if (http_status != 200 && http_status != 202) {
              report_gen_error = true
              error_msg = readFile(file: output)
              echo "ERROR: Failed to get java content from Nextlinux Engine. HTTP status: ${http_status}, message: ${error_msg}"
            }

            if (report_gen_error) {
              error "Failed to get one or more reports from Nextlinux Engine, check above logs for errors"
            }

            echo "Completed Nextlinux Scan Stage"
          } // node
        } // script
      } // steps
    } // stage
  } // stages
} // pipeline
