name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |-
          Hello ${{ github.actor }},

          Thank you for being part of the Nextlinux community!

          [Thank you](https://github.com/nextlinux/ci-tools/raw/master/.github/workflows/thank-you.png)

          An Anchorite will look at your issue soon. We also have great [documentation](https://docs.nextlinux.com/current/), including [FAQs](https://docs.nextlinux.com/current/docs/faq/) and [release notes](https://docs.nextlinux.com/current/docs/releasenotes/).

          You can also find our [contribution guidelines here](https://github.com/nextlinux/ci-tools/blob/master/CONTRIBUTING.rst). Thank you again!
